@startuml

hide footbox
skinparam sequenceMessageAlign center
skinparam sequenceArrowFontSize 11
skinparam noteFontSize 11
skinparam monochrome true
skinparam lifelinestrategy solid


rnote over "End User", "Device Application"
     "End User installs a new Device Application
      containing a SAM script"
end rnote

"Device Application" -> LAA : install(sessionId, samServiceIdentifier, samSMFQDN, localScriptUri)

rnote over "LAA", "SAM SD"
     [0] Process getSAMEligibilityData
end rnote

"LAA" -> "LAA" : install(sessionId, samServiceIdentifier, samEligibilityData)

rnote over "LAA", "End User"
     [1] End User interactions for user intent
end rnote

rnote over "LAA", "SAM SD"
     [2] Process executeGPSERAMScriptFile(sessionId, localScriptUri)
end rnote

LAA --> "Device Application" : notification(sessionId, samServiceIdentifier, INSTALL)

LAA --> "SAM SM" : notification(sessionId, samServiceIdentifier, INSTALL)
@enduml
